### ISSUE TITLE
End-of-program file flushing seems to not work

### ISSUE THREAD

**Issue by sezata** [sezata/trigger_daq#25]
This is Alex from Ann's laptop.

The end-of-program file flushing seems to not work. I have no idea why. We're running with no beam, where the only expect input data is a misfire scintillator coincidence every 20-30 seconds. If I run the script, it tells me it's receives data every 20-30 seconds, which is great, but when I Ctrl+C, no data is written to file. Very confusing.

This can be ameliorated by flushing after every write. Then all the data is correctly recorded. But this is slow when there's a large input data rate. TO BE UNDERSTOOD.

Here are some printouts: data is received and looks sensible; it writes to an open file; Ctrl+C; an open file is closed; but then there's nothing in the file at the end of the day. ls and du confirm there's nothing on disk.

``` 
processPacket :: writing A200E254 <open file 'mmtp_test_23.dat', mode 'w' at 0x1063050c0>
processPacket :: filename mmtp_test_23.dat
processPacket :: writing 6AEEF5D2 <open file 'mmtp_test_23.dat', mode 'w' at 0x1063050c0>
processPacket :: filename mmtp_test_23.dat
>>> Stopped!
>>> Closing files...
<open file 'mmtp_test_23.dat', mode 'w' at 0x1063050c0>
Closing :: Before write 0
Closing ::  After write 0
<closed file 'mmtp_test_23.dat', mode 'w' at 0x1063050c0>
```

**Comment by alexandertuna** [comment]
www.cern.ch/tuna/mwe.py

**Comment by alexandertuna** [comment]
Work around for now by flushing every event. Lar tested with 10s kHz of input test data and it seemed fine. May revisit this later.
