### ISSUE TITLE
Fit decoder treats VMM,CH = 0,0 as "no hit", even when it's a real hit

### ISSUE THREAD

**Issue by alexandertuna** [sezata/trigger_daq#5]
![image](https://cloud.githubusercontent.com/assets/3323802/25776705/26cc8514-3294-11e7-9d44-926ad7e50780.png)

**Comment by sezata** [comment]
I'm going to fix this, but I actually think it isn't a problem in the case of the offsets because the strip should be nonzero even if it's (VMM, CH) = (0,0)
