### ISSUE TITLE
Add an integer to the TP fit TTree which says how many hits are present

### ISSUE THREAD

**Issue by alexandertuna** [sezata/trigger_daq#8]
It would make looping over / drawing hits easier. Suggestion: ```tpfit_n```.

e.g. 

```tree->Draw("mxlocal", "tpfit_n==7 || tpfit_n==8")```

or

```
for i in xrange(tree.tpfit_n): 
    print tree.tpfit_CH[i]
```

**Comment by sezata** [comment]
Moved to MMFE8_DataFormats
